package com.revature;

public class Driver {

	public static void main(String[] args) {
		String s="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis faucibus nisi, non fermentum risus. Vestibulum convallis, risus vel sollicitudin lacinia, risus lectus pharetra felis, vitae sagittis purus tortor eu mi. Ut rhoncus gravida sapien sed lacinia. Nunc rhoncus erat non luctus elementum. Nulla lobortis, enim et varius molestie, massa enim volutpat massa, id aliquam justo sapien in ligula. Proin vel tortor scelerisque, pharetra ligula ac, ultrices enim. Morbi eu augue in eros ultricies vulputate id non felis. Curabitur ac sapien eget turpis vehicula pellentesque ac a leo. Maecenas mollis, odio id laoreet varius, leo erat faucibus odio, non lobortis justo odio vitae lorem. Ut pharetra sapien quis tortor commodo, et feugiat tortor eleifend. Praesent faucibus lorem non maximus ullamcorper.\r\n"
				+ "\r\n"
				+ "Pellentesque vel malesuada dui. In felis orci, pharetra eget orci sed, imperdiet congue sapien. Suspendisse sodales cursus lorem, non imperdiet massa viverra in. Quisque sollicitudin volutpat ipsum consectetur euismod. Nam blandit lorem eu magna iaculis, bibendum elementum tellus dapibus. Sed viverra elementum sapien, sed dapibus dui tincidunt ut. Suspendisse potenti. Etiam pulvinar, urna vel viverra sagittis, sem eros volutpat enim, in venenatis ligula nisl at tellus. Phasellus iaculis ante sed neque varius, eu ultricies enim aliquet. Maecenas maximus quam lectus, vel porta ipsum aliquet id. Integer ultricies posuere placerat.\r\n"
				+ "\r\n"
				+ "Fusce vel tortor eu ligula sollicitudin rutrum. Quisque risus tortor, porttitor ac ipsum nec, feugiat consectetur urna. Sed iaculis diam vel rutrum semper. Curabitur viverra odio nec magna facilisis, in rhoncus neque cursus. Nam eu rhoncus justo. Donec sed ligula mi. Vivamus sapien nulla, aliquam eget odio quis, efficitur rhoncus mi. Ut commodo lacus eu ante auctor consectetur. Pellentesque vitae sodales turpis. Quisque pharetra sed elit vel ultrices. Praesent pulvinar, quam quis vehicula ultricies, ipsum ipsum lobortis mauris, semper suscipit mi elit dictum ante. Cras commodo mauris non quam molestie, et pretium neque fringilla.\r\n"
				+ "\r\n"
				+ "Morbi finibus faucibus cursus. Duis tempor leo sit amet purus suscipit, at laoreet lorem pharetra. Aenean eget tempus lorem. Nunc arcu sem, blandit vel turpis mollis, cursus sodales odio. Sed venenatis, risus ut elementum venenatis, sem arcu pharetra dolor, vitae ullamcorper quam elit non nunc. Nunc quis semper nisl, eget semper nisi. Maecenas lorem ante, sodales nec iaculis congue, aliquam in est. Nullam non scelerisque dolor. Phasellus venenatis ex nec efficitur ornare. Morbi non mi enim. Quisque et placerat neque. Integer et lobortis tortor, pulvinar ullamcorper nunc.\r\n"
				+ "\r\n"
				+ "Sed quis accumsan diam. Suspendisse lectus ligula, elementum non turpis nec, sodales ornare nunc. Aliquam congue diam sem. Ut rutrum est quis nunc ultricies, eget lacinia nisl porttitor. Fusce blandit, justo nec condimentum mollis, diam eros maximus leo, nec ultrices lacus felis auctor neque. In ut commodo orci. Nam vitae blandit metus, in vulputate est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris ante purus, rhoncus non libero ac, pretium faucibus urna. Quisque lobortis, tortor vel sodales tincidunt, ante turpis tempor metus, in blandit dolor nunc in velit.\r\n"
				+ "\r\n"
				+ "Morbi iaculis, massa nec sagittis commodo, massa justo aliquam lectus, vel maximus lacus mauris feugiat risus. Donec ultricies dui erat, placerat facilisis risus bibendum eget. Sed ante ligula, auctor eu neque quis, sollicitudin ultricies turpis. Aliquam odio nibh, tristique rutrum mattis quis, elementum non turpis. Nullam neque felis, dictum nec enim non, placerat malesuada arcu. Fusce sit amet auctor massa. In vitae lobortis quam, sed suscipit orci. Pellentesque at lacus non augue posuere tincidunt. Nam ultricies dignissim lacus, sit amet dapibus sem interdum et. Praesent id tortor sodales, iaculis nulla eget, tempus eros.\r\n"
				+ "\r\n"
				+ "Maecenas accumsan, elit et blandit ullamcorper, odio risus feugiat leo, faucibus porta nulla magna rutrum nunc. Sed in mauris dui. Phasellus vel tempor tortor. Aenean id venenatis nulla, vitae pulvinar justo. Aliquam venenatis, nibh quis tempor pharetra, lorem tellus aliquet tortor, a iaculis ipsum nunc eget enim. Nulla facilisi. Sed tincidunt sodales augue, fringilla sollicitudin diam sollicitudin in.\r\n"
				+ "\r\n"
				+ "Cras molestie quis justo non mattis. Nam mattis volutpat nisi, nec aliquet leo. Fusce pellentesque lorem quis auctor porttitor. Etiam mi turpis, laoreet quis suscipit a, placerat eu metus. Morbi blandit efficitur augue, a accumsan urna efficitur id. Vestibulum eu sagittis nibh. Praesent dictum vitae nisi efficitur accumsan. Fusce at orci mauris. Nullam eleifend risus quam, ac facilisis turpis maximus vitae. Vestibulum et faucibus neque. Phasellus ante lacus, bibendum a urna in, facilisis mattis ex. Etiam ut ex at metus sollicitudin ultricies sit amet sed odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n"
				+ "\r\n"
				+ "Sed at accumsan augue. Suspendisse viverra scelerisque venenatis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin quis est lorem. Duis sed tempor erat, id laoreet ante. Fusce euismod imperdiet tellus. Vestibulum malesuada ultricies aliquet. In finibus volutpat erat, sed efficitur dui mollis et. Maecenas vitae massa vel velit commodo dictum eget non nibh.\r\n"
				+ "\r\n"
				+ "Cras tincidunt augue consectetur, placerat diam a, vulputate nisi. Maecenas a lacinia justo, at aliquet arcu. Quisque gravida dignissim porta. Quisque viverra sem ex, eget hendrerit ex dapibus at. Praesent sollicitudin sem risus, non eleifend mi sagittis auctor. Cras vehicula lorem quis imperdiet feugiat. Aliquam varius mauris id pharetra fringilla. Proin tempus rutrum turpis, nec pretium ex mollis vitae.\r\n"
				+ "\r\n"
				+ "Proin ac justo accumsan, posuere ipsum ac, commodo massa. Proin dignissim ante ligula, vel luctus orci dictum at. Mauris nec diam aliquam, congue ante sed, laoreet purus. Sed suscipit risus quam, quis varius risus molestie vitae. Etiam molestie, tellus et imperdiet tincidunt, metus massa sodales metus, ac scelerisque tortor ipsum ac neque. Aliquam maximus dui eget maximus sollicitudin. Sed sed mi vitae arcu dapibus placerat. Sed consequat fringilla lacus, non elementum ligula dapibus sit amet. Phasellus vel nulla ut ante maximus dictum. Praesent at nunc pharetra, ultricies leo ac, fermentum urna. Nullam ullamcorper tortor at nisl tristique maximus. Maecenas suscipit est aliquam libero venenatis ultricies. Duis blandit, nibh a tempor laoreet, augue metus varius ipsum, a vulputate nunc eros id tellus.\r\n"
				+ "\r\n"
				+ "Quisque turpis purus, egestas ac turpis eget, aliquet lacinia nibh. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec eleifend faucibus ante, a facilisis elit dictum et. Vivamus pharetra metus nec massa malesuada, nec tincidunt arcu faucibus. Cras eget mollis leo. Ut vel ipsum suscipit, imperdiet arcu quis, fringilla tortor. Aliquam erat volutpat. Aliquam consequat tellus leo. Ut et felis vitae metus ullamcorper vehicula in vel leo. Mauris gravida tristique tristique. Vestibulum cursus sit amet magna commodo dapibus. In rutrum tincidunt sapien, nec pellentesque lorem finibus non. Suspendisse odio felis, bibendum vel neque in, volutpat tincidunt est. Cras non augue eget odio bibendum commodo in in est. Nunc diam augue, tincidunt id luctus id, ullamcorper ac nisl.\r\n"
				+ "\r\n"
				+ "Nulla vulputate lorem a augue varius cursus. Suspendisse in est euismod augue finibus volutpat non sed urna. Vestibulum quis suscipit dui. Morbi non nisl nisi. Donec semper, velit eget tristique rhoncus, orci lacus pulvinar risus, in eleifend lectus enim vel neque. Vivamus fermentum nisl elit, at finibus velit tempus id. Vestibulum malesuada mi quis dui viverra, vel fermentum risus blandit. Curabitur eget velit vulputate ipsum hendrerit volutpat. Suspendisse semper, mi quis pharetra elementum, mi ligula facilisis felis, in egestas diam libero in eros. Aenean aliquam, enim nec placerat finibus, justo elit euismod tortor, non pharetra augue dui quis nunc.\r\n"
				+ "\r\n"
				+ "In egestas arcu vitae nisl faucibus mattis. Curabitur luctus risus ac arcu ultricies pretium. Sed eu sapien posuere, fermentum arcu sed, dictum nibh. Donec dapibus varius justo sit amet finibus. Donec id dui efficitur, fringilla mauris a, porttitor enim. Sed volutpat lobortis nisi, in viverra eros malesuada ut. Proin pretium, nulla in eleifend aliquam, risus felis eleifend magna, ut luctus lectus ipsum maximus purus. Phasellus id ipsum aliquam, maximus neque accumsan, porttitor neque. Ut quis nisl efficitur, tristique metus a, tempor dolor. Suspendisse interdum augue feugiat nunc consectetur convallis. Duis convallis ex vitae libero elementum, sit amet pellentesque urna congue. Vestibulum eu faucibus lectus, nec sodales lectus. Aliquam tincidunt purus ex, vel ultricies quam auctor id. Sed molestie rutrum iaculis.\r\n"
				+ "\r\n"
				+ "Nunc pharetra dolor vel pulvinar elementum. Aenean feugiat mattis ex at ornare. Suspendisse luctus massa quis facilisis efficitur. Curabitur porttitor ante sem, sit amet bibendum ex facilisis eget. Suspendisse sed consequat arcu, eu finibus nisl. Nulla facilisi. Quisque ornare sapien a lectus tempus euismod. Vestibulum vitae risus urna. Nunc tempor porttitor fermentum. Nulla tristique ligula egestas nibh congue, ac auctor massa pretium. Integer pharetra nulla quis est sollicitudin feugiat. Morbi eu velit vestibulum, blandit mauris eu, tincidunt tortor. Maecenas nunc lorem, iaculis id convallis quis, accumsan at nulla. Ut ut condimentum mauris, ac aliquam eros.\r\n"
				+ "\r\n"
				+ "Quisque cursus elit vitae magna placerat, vel venenatis magna accumsan. Vestibulum quis nulla erat. Maecenas dignissim tortor id nunc tristique, sit amet consequat mauris convallis. Suspendisse non consequat lorem. Duis pharetra felis vitae lectus lacinia, et cursus nisi sodales. Fusce scelerisque porta consectetur. Morbi porttitor, lacus a bibendum efficitur, elit odio iaculis tortor, at vestibulum turpis nisl in libero. Nulla lacinia, dui a suscipit euismod, justo diam malesuada neque, in auctor justo justo non nisi. Aenean ac sapien eu neque scelerisque convallis id sed quam. Vivamus nec volutpat nulla.\r\n"
				+ "\r\n"
				+ "Sed bibendum quam ut volutpat tempus. In semper pellentesque imperdiet. Aliquam semper tellus venenatis ipsum cursus, ut semper orci blandit. In lorem nunc, posuere nec pharetra eu, egestas id dolor. Integer lobortis ligula hendrerit metus lacinia commodo. Proin malesuada dui at dolor condimentum, sed fermentum neque faucibus. Vestibulum hendrerit ante in dictum bibendum. Morbi egestas nisi non ligula elementum venenatis. Curabitur eget porta turpis, sed malesuada purus. Mauris sit amet facilisis massa. Maecenas dignissim a lorem non placerat. Aliquam lobortis, turpis non dapibus vehicula, odio lacus mattis justo, scelerisque tempus ipsum nibh dapibus orci. Sed auctor, dui vitae faucibus mattis, turpis sem gravida sem, sed fringilla sem justo ut massa.\r\n"
				+ "\r\n"
				+ "Duis interdum risus at tellus ullamcorper pharetra. Aenean eget enim pellentesque, rutrum massa ac, pellentesque tortor. Sed viverra justo non urna gravida commodo. Vivamus pharetra, massa nec porta fermentum, eros orci finibus tellus, ut bibendum purus tellus eu tellus. Quisque quis quam vitae ligula gravida facilisis vitae vel nisi. Duis ac arcu non risus pharetra placerat. Sed ac enim id dui semper maximus in at dolor. Pellentesque facilisis faucibus felis at posuere. Aliquam ante neque, aliquet ac massa ac, luctus mattis mauris. Cras ac pretium mi, sit amet pellentesque turpis. Aliquam vitae posuere tellus. Cras nunc est, bibendum id egestas iaculis, feugiat sit amet massa.\r\n"
				+ "\r\n"
				+ "Aliquam scelerisque, dui tincidunt molestie tristique, dui ipsum tempor nisi, a semper lacus tortor feugiat orci. Etiam purus justo, accumsan quis feugiat vel, blandit sit amet arcu. Curabitur vitae tellus nibh. Proin sit amet neque sit amet est blandit maximus. Praesent sed augue congue orci placerat scelerisque. Ut sit amet dolor justo. Integer tempus, libero quis convallis elementum, tortor leo sodales neque, id porta eros ex ac enim. Duis ornare quam non nulla suscipit, a rhoncus metus interdum. Sed et nisi vel turpis hendrerit fringilla. Pellentesque dictum, sem sed pretium lobortis, libero nulla faucibus augue, et eleifend nulla felis quis leo. Fusce quis diam massa. Donec dictum libero sed dui convallis, vitae lobortis nisi fringilla. Maecenas laoreet, magna ac dignissim suscipit, lacus justo porta neque, eu fringilla eros nisl sit amet nisi.\r\n"
				+ "\r\n"
				+ "Nam orci orci, porttitor lobortis quam quis, interdum ultrices mauris. Cras nec ante nec erat euismod bibendum. Nulla malesuada a est nec vehicula. Etiam eu facilisis purus. Cras posuere volutpat lacus, ac faucibus felis placerat euismod. Nam a sodales libero, ut pulvinar arcu. Maecenas id tellus non ante cursus tempor. Aliquam imperdiet iaculis elementum. Duis ornare lorem et mi mattis rutrum in mollis nisl. Nam augue ex, fermentum non purus quis, suscipit dapibus arcu. Vivamus rhoncus feugiat eros ut vulputate. Cras bibendum placerat ante, id euismod tortor porttitor eget. Aliquam sagittis elit turpis, nec accumsan sapien vehicula vel. Donec bibendum odio elit, non tincidunt ipsum dictum ut. Mauris dictum sapien tincidunt, sollicitudin metus sit amet, vehicula dui.\r\n"
				+ "\r\n"
				+ "Integer fringilla dui eu nisi commodo pretium. Vivamus id tincidunt mauris. Vivamus justo turpis, porttitor sit amet rutrum id, consequat et erat. In tortor arcu, cursus id est vel, fringilla finibus mauris. Nulla ultrices ante at massa porttitor vehicula. Integer dictum eleifend dolor ac tempor. Sed non viverra leo. Cras pulvinar tellus vitae elit suscipit, id suscipit ipsum aliquet. Vestibulum ullamcorper leo non sapien semper, ut bibendum orci sodales. Phasellus in vestibulum lacus, eu sagittis ligula.\r\n"
				+ "\r\n"
				+ "Mauris mollis massa sed nisl tincidunt, imperdiet sagittis lacus elementum. Nulla nec mi turpis. Cras malesuada sapien sit amet rhoncus tincidunt. Integer gravida dui arcu, nec placerat augue laoreet in. Nam scelerisque, diam eu hendrerit malesuada, est quam iaculis nisi, ut mattis massa lorem non diam. Etiam a vehicula lacus. Proin vitae tincidunt metus. Proin elementum libero et urna fermentum bibendum. Aliquam turpis est, maximus et velit id, tempus finibus mauris. Sed eu magna sem. Cras eget lacus non diam elementum luctus. Nunc pellentesque rhoncus vulputate. Duis facilisis eget ex eu dignissim. Integer sed molestie tortor.\r\n"
				+ "\r\n"
				+ "Aenean risus leo, scelerisque non convallis vitae, fringilla sit amet orci. Etiam euismod felis tellus, in condimentum sem interdum posuere. Vivamus quis eros viverra, faucibus tellus vel, iaculis lorem. Cras congue nibh sodales, semper nisi ut, imperdiet arcu. Pellentesque venenatis, purus eu luctus posuere, odio nisi semper felis, et vehicula augue magna a lacus. Nunc rutrum cursus ipsum. Ut malesuada sem metus, sed pretium odio tristique quis. In viverra augue magna, sed finibus erat fringilla vel. Mauris vel tellus felis. Etiam et tempor purus. Donec vulputate, magna sit amet convallis bibendum, eros eros malesuada massa, ut mollis nulla tellus id ante. Nam rhoncus mauris enim, sit amet commodo massa dignissim nec. Sed ultrices, arcu vel imperdiet rutrum, nulla erat laoreet tortor, in dapibus velit quam vel nisl.\r\n"
				+ "\r\n"
				+ "Sed a lectus erat. Donec sed finibus ante. Morbi commodo libero nulla, vitae dictum urna suscipit sed. Donec pretium feugiat elit non sagittis. Sed sapien risus, molestie vitae ultrices a, tristique quis dui. Curabitur eu mauris dolor. Nulla vehicula turpis nec vestibulum posuere. Nam metus sapien, pharetra quis pellentesque vitae, eleifend id mi. Aliquam nec nisl placerat, luctus magna vitae, porttitor justo. Morbi pharetra libero in nisl fringilla rhoncus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla sagittis vitae sapien a malesuada. Donec sed magna in lacus vulputate maximus.\r\n"
				+ "\r\n"
				+ "Nullam semper, quam id maximus egestas, sapien mi viverra mauris, id elementum tortor ipsum a lorem. Praesent quis suscipit velit. Duis fermentum, mi congue mattis imperdiet, purus mauris maximus leo, non sodales massa felis sodales orci. Etiam non ex rutrum, ornare felis vitae, maximus lectus. Donec eu vulputate justo, sed vulputate augue. Aenean sodales bibendum lacus, quis sagittis enim tempor at. Donec eu eros ultrices, mollis tellus ac, aliquet sem. Quisque blandit tortor at pellentesque luctus. Etiam pulvinar nunc at neque eleifend, et iaculis lacus interdum. Ut magna magna, varius ut ex quis, mattis pellentesque metus. Vestibulum convallis justo odio, nec iaculis ligula condimentum ac. Donec at gravida odio. Ut pretium vel enim et hendrerit. Praesent aliquet vehicula lectus, ac venenatis nisl.\r\n"
				+ "\r\n"
				+ "Duis porttitor fermentum odio, sed fringilla massa sagittis sed. Aliquam pulvinar quam nisi, et congue ex ornare consectetur. Donec feugiat felis sit amet nibh mollis ullamcorper. Nam consequat, nulla at efficitur volutpat, erat magna efficitur lorem, ut pharetra velit turpis vitae dolor. Aliquam venenatis rutrum mollis. Duis nec dapibus nunc, id finibus ipsum. Phasellus et leo vel ante tristique finibus eget luctus eros. Vivamus quam elit, elementum faucibus sapien dignissim, luctus commodo quam. Morbi placerat sapien non eros consectetur, nec tincidunt massa malesuada. Nam semper posuere mi a lobortis. Morbi at lorem porta, posuere est at, cursus ligula. Nullam suscipit justo sit amet sem ullamcorper, a euismod eros sagittis. Sed ultrices dolor libero, vitae venenatis lorem sollicitudin sit amet. Nunc auctor efficitur ligula, at pellentesque augue ornare ac. Ut fermentum efficitur lacinia.\r\n"
				+ "\r\n"
				+ "Ut quis libero vel arcu hendrerit facilisis vestibulum in eros. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean sit amet sapien sit amet leo molestie malesuada. Sed feugiat nulla nec placerat scelerisque. Morbi semper cursus quam id pulvinar. Sed lobortis massa eu posuere elementum. Fusce posuere quis ligula sed cursus.\r\n"
				+ "\r\n"
				+ "Donec at tellus a risus mattis bibendum sit amet in lacus. Maecenas vulputate tellus ac turpis vestibulum ultricies efficitur pretium augue. Nam eu nunc gravida, venenatis erat eget, lobortis enim. Pellentesque et tortor interdum, volutpat erat sed, tempor nisl. Aliquam pulvinar maximus massa, at tincidunt orci luctus eget. Proin mi nibh, laoreet vitae dictum et, viverra id purus. Pellentesque nec efficitur felis, faucibus sodales quam. Morbi molestie id quam ut mattis. Aliquam ornare tristique diam, quis volutpat est eleifend a. Etiam vel libero sit amet est pellentesque malesuada.\r\n"
				+ "\r\n"
				+ "Vestibulum id molestie lacus, vitae ornare nibh. Vivamus sit amet felis lectus. In tincidunt imperdiet nibh eget viverra. Quisque orci turpis, tincidunt id libero venenatis, luctus varius tellus. Proin feugiat felis tincidunt libero tincidunt vestibulum. Proin quis eros non augue porttitor vulputate a eu sapien. Praesent consectetur, neque et suscipit accumsan, enim felis tristique ante, eu posuere lacus metus eget risus.\r\n"
				+ "\r\n"
				+ "Ut mollis est ipsum, nec volutpat ante convallis sed. Phasellus porta turpis maximus nisl ultrices, a pellentesque mauris venenatis. In sapien lorem, ultricies a volutpat et, mattis vel ex. Vivamus in nunc eu ante sagittis pulvinar non quis tortor. Nam vestibulum malesuada ligula, eget eleifend risus bibendum porta. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sagittis eros turpis, eget dapibus velit auctor sit amet. Quisque in odio non nibh faucibus euismod sed eu massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non eros sem. Donec metus odio, dictum id enim eu, auctor pharetra elit.\r\n"
				+ "\r\n"
				+ "Nam a est non arcu pellentesque aliquam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean ac nulla in enim tincidunt varius sit amet a neque. Sed et felis consequat, accumsan arcu vel, viverra dui. Sed ac bibendum enim. Nam in elit congue, lobortis lorem non, volutpat nisl. Etiam velit tortor, lacinia ut lobortis a, tempus venenatis elit. Proin tincidunt justo mi, eu molestie nulla rutrum ut. Suspendisse vitae augue a mauris egestas iaculis. Etiam accumsan nisl libero, id gravida sem dictum vitae. Quisque rutrum pharetra enim, eu venenatis turpis. Cras fringilla diam arcu, ut malesuada elit dapibus quis.\r\n"
				+ "\r\n"
				+ "Nulla facilisi. Nullam vitae luctus lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam tempus sit amet elit nec luctus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut volutpat metus eu maximus condimentum. Quisque tristique magna nisl, vel interdum ante egestas vestibulum. Donec volutpat odio nisi, id egestas ex sollicitudin id. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed consequat, elit nec porttitor fermentum, neque ligula sollicitudin ligula, in pulvinar est elit eget metus.\r\n"
				+ "\r\n"
				+ "Pellentesque egestas maximus felis, et egestas augue faucibus vitae. Ut rhoncus vel erat elementum tristique. Nam tempor tristique risus vel blandit. Curabitur vitae pellentesque est. Aliquam efficitur augue eget est tristique, id posuere ante elementum. Sed diam eros, sollicitudin sit amet dictum vitae, feugiat eget metus. Morbi euismod semper risus, ultricies pharetra tellus lobortis ac. Quisque ultrices ante nec consectetur rhoncus. Nulla sit amet arcu hendrerit, viverra ante vel, mollis quam. Phasellus finibus, nulla id facilisis iaculis, ipsum leo ultrices est, quis consequat orci magna a augue. Pellentesque sodales velit eu euismod rhoncus. Phasellus consectetur ligula turpis, pretium ultrices massa lobortis id.\r\n"
				+ "\r\n"
				+ "Mauris a malesuada turpis. Mauris tellus nulla, tempus sit amet hendrerit sed, luctus eu augue. Nulla nec nisi eu felis egestas molestie. Quisque efficitur vitae metus sed viverra. Ut molestie scelerisque sem. Vivamus at nibh non eros varius accumsan eu et nunc. Donec tincidunt, nunc ut feugiat pharetra, lorem enim dictum erat, id pellentesque ex est sit amet magna. Donec porta enim pretium metus fermentum, ac tincidunt neque vulputate. Nunc molestie ornare arcu, non gravida arcu ullamcorper sit amet. Mauris ultricies commodo imperdiet. Donec facilisis porta lorem, quis vulputate eros aliquam id.\r\n"
				+ "\r\n"
				+ "Donec tempor interdum ante, sit amet efficitur ex pulvinar ut. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec ullamcorper massa ligula, quis facilisis dolor consequat sit amet. Fusce felis augue, hendrerit sagittis enim eget, ultricies vulputate elit. Suspendisse interdum, velit pulvinar pharetra luctus, orci felis lobortis sem, at finibus nibh neque in nibh. Suspendisse tortor metus, sollicitudin nec vehicula a, blandit at neque. Vestibulum in faucibus lorem. Donec tempor, arcu quis sagittis mollis, nibh lorem elementum mi, nec viverra libero ligula auctor justo. Aliquam eu gravida nisi. Pellentesque at quam finibus, auctor felis dapibus, auctor ante. Nullam sit amet volutpat velit. Curabitur finibus luctus ultrices. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas vehicula sem ut urna lacinia auctor.\r\n"
				+ "\r\n"
				+ "Duis venenatis, augue eu euismod vestibulum, erat elit dignissim libero, at blandit purus ligula nec nisl. Ut viverra rutrum convallis. Praesent tempor nibh non ante feugiat venenatis. Donec volutpat, dolor nec dictum volutpat, eros diam rhoncus elit, porta vehicula est diam at sem. Pellentesque in massa porta, tempor elit vitae, dapibus urna. Aenean a venenatis dui. Donec condimentum leo id posuere dapibus. Cras scelerisque, nisl in accumsan dignissim, metus nunc aliquam mauris, et rutrum metus velit quis massa. Aenean lorem purus, eleifend eget suscipit vitae, placerat et velit.\r\n"
				+ "\r\n"
				+ "In dapibus pretium magna eu varius. Nullam sed erat commodo, dignissim lectus at, pulvinar urna. Integer in mi ipsum. Nullam ut metus vestibulum, semper sapien eu, aliquam erat. Sed ut est enim. Suspendisse potenti. Proin vitae tellus nibh.\r\n"
				+ "\r\n"
				+ "Aliquam maximus vulputate lectus, ac pellentesque leo ultricies ac. Suspendisse potenti. Aenean finibus quam tempus tortor placerat luctus. Etiam tempus a urna eget imperdiet. Vivamus tincidunt, purus et placerat mollis, turpis nisl dapibus arcu, sit amet efficitur nisl orci fringilla ligula. Maecenas egestas enim velit, tempus condimentum erat auctor nec. Aenean eu pulvinar orci. Sed ut tempus tellus. Suspendisse non venenatis odio. Maecenas tincidunt auctor erat nec tempor. Mauris sollicitudin magna turpis, porttitor porttitor nisi ullamcorper in. Maecenas vulputate neque eget facilisis rutrum.\r\n"
				+ "\r\n"
				+ "Nullam at metus tempor, sagittis purus nec, consectetur neque. Ut volutpat consectetur erat, quis ullamcorper magna ullamcorper in. Donec tincidunt quam nec lacus ultricies sagittis eget in neque. Cras tincidunt orci et sem viverra, vel aliquam leo congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam vulputate mattis dui, ac interdum magna efficitur eget. Proin varius mi metus, vel ultricies tellus vehicula in. Mauris gravida iaculis ipsum ultricies imperdiet. Nulla aliquet posuere nisi vitae sollicitudin. Cras dictum nulla ut felis suscipit, nec interdum sem fermentum. Proin et laoreet ex. Sed fringilla vulputate velit rhoncus dictum. Proin et malesuada dui. Nunc quis convallis nibh. Proin maximus luctus tellus, eget laoreet diam tincidunt id. Ut fermentum aliquet laoreet.\r\n"
				+ "\r\n"
				+ "Quisque sollicitudin euismod sodales. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin non purus tristique, tristique ante ac, suscipit diam. Duis pharetra diam in ligula mattis, eu efficitur velit mollis. Curabitur sollicitudin, ipsum sit amet auctor tincidunt, lacus quam lobortis dolor, vel malesuada nibh justo sed diam. Maecenas augue lacus, scelerisque vel pretium ut, scelerisque et sapien. Proin interdum elit hendrerit purus blandit, et commodo eros euismod. Sed placerat elit dictum tellus scelerisque mollis. Sed dapibus lorem et neque lobortis porta. Fusce imperdiet neque nulla, quis tincidunt mi efficitur id. Sed blandit non sapien ut fermentum. Integer posuere tempor risus ut lobortis. Aliquam in feugiat nisi, sed tincidunt eros. Nulla auctor enim sodales faucibus egestas.\r\n"
				+ "\r\n"
				+ "In accumsan varius ultricies. Fusce in orci at turpis pretium rutrum vitae in eros. Etiam et volutpat ipsum, non finibus nibh. Cras facilisis orci vel lectus maximus ultrices. Vestibulum sed cursus nunc. Quisque accumsan ullamcorper lacus, a condimentum nunc lacinia a. Etiam quis felis et nulla scelerisque dapibus vestibulum non est.\r\n"
				+ "\r\n"
				+ "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas et nulla vitae erat imperdiet gravida luctus at neque. Etiam hendrerit vitae lorem non ullamcorper. Sed eleifend lorem et neque feugiat, vitae ultrices ex ornare. Aliquam pretium feugiat turpis eu vestibulum. Nulla egestas tortor a ipsum convallis, et lacinia ligula vestibulum. Sed elit sem, venenatis sollicitudin mi in, viverra efficitur ante.\r\n"
				+ "\r\n"
				+ "Nulla non hendrerit nunc. Sed consectetur ac mauris quis varius. Cras sed velit elit. Sed et lectus mauris. Praesent velit ipsum, convallis in purus a, venenatis tempor justo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tempus elit vel augue porta venenatis. Sed non semper justo. Phasellus a gravida lorem. Nulla nisi leo, auctor a metus eget, dictum porta lectus. Vestibulum ultricies interdum nibh, ut porttitor dolor convallis id. Nam blandit orci at tortor rutrum, interdum dignissim tortor dictum. Nulla imperdiet justo vitae eros sodales porttitor. Nulla ex sapien, elementum et ullamcorper a, mattis nec justo. Maecenas suscipit convallis metus, quis vehicula ex. Aenean ultricies purus elit, vitae vestibulum massa feugiat ac.\r\n"
				+ "\r\n"
				+ "Donec efficitur, ex eu iaculis convallis, felis tortor blandit eros, ultricies molestie lacus est tincidunt diam. Vivamus at accumsan purus. Vivamus non pellentesque nisi. Nullam ac vulputate dolor. Praesent lacus mi, gravida at tempor nec, semper et diam. Nullam sit amet enim ex. Nulla facilisi. Vivamus nulla dui, laoreet ut sodales id, congue vel neque. Aenean efficitur sit amet metus in sollicitudin. In malesuada justo non erat scelerisque efficitur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam sit amet mauris a enim euismod commodo fringilla non mauris.\r\n"
				+ "\r\n"
				+ "Vestibulum enim sem, sagittis at placerat nec, mattis sit amet nisl. Morbi gravida aliquet porttitor. Nullam condimentum arcu eget dui ullamcorper, in semper ante efficitur. Nam gravida, tellus sed scelerisque iaculis, felis nibh ornare mi, at feugiat augue ipsum eget tortor. Donec eget purus quis lacus aliquet fringilla vitae id magna. Sed ullamcorper felis in arcu malesuada ullamcorper. Cras quis tempor dolor. In aliquet pretium nunc in dictum. Sed euismod mauris ut est feugiat, non elementum ligula tempus.\r\n"
				+ "\r\n"
				+ "Fusce scelerisque ligula quam, eget tempus justo porta ut. Nulla pretium nunc ante, ac vulputate ligula rhoncus sodales. Vivamus ullamcorper orci ac dui euismod cursus. Vestibulum ac orci non arcu pulvinar sodales ac auctor dolor. Nunc blandit maximus augue. Sed non ex id felis dictum blandit in ac enim. Integer sit amet maximus ligula. Ut massa justo, placerat quis blandit ut, ultricies in nisi. Fusce suscipit euismod arcu, nec efficitur elit porta in. Nullam luctus mattis dui. Donec tristique interdum rhoncus. Fusce ultricies massa vel elit sodales dignissim. Quisque faucibus vehicula ipsum, sed pharetra turpis blandit id.\r\n"
				+ "\r\n"
				+ "Praesent lobortis eros ac metus ullamcorper, a malesuada ex vehicula. Morbi vel nibh ex. Sed pharetra porta vestibulum. Pellentesque ut iaculis arcu, id dignissim turpis. Maecenas a accumsan turpis, vel dictum turpis. Donec sagittis libero magna, vel tempus nisl laoreet elementum. Maecenas vestibulum fermentum dapibus. Sed est ipsum, posuere non vestibulum eu, dictum in dolor. Donec a placerat nisl. Cras hendrerit, eros in sagittis egestas, urna turpis eleifend odio, sit amet egestas odio odio ac urna. Etiam mattis mi ut risus ullamcorper dictum. Praesent ullamcorper tempus nulla, congue eleifend arcu molestie in. Aliquam pretium lorem tellus, eu congue sapien dapibus et.\r\n"
				+ "\r\n"
				+ "Duis vel elit ut orci efficitur dictum. Donec pulvinar tortor magna, quis dapibus lectus iaculis sed. Pellentesque ut lorem eu elit cursus tincidunt et eu sapien. Integer fermentum, turpis gravida scelerisque condimentum, lectus mi feugiat turpis, quis finibus turpis leo non lacus. Nulla tempor, lectus in feugiat placerat, felis ex condimentum justo, eu viverra risus odio sagittis magna. Morbi gravida mollis volutpat. Maecenas vel elit tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ornare tempus nulla, sit amet viverra turpis tincidunt eget. Donec quis lacus lectus. Proin lobortis ultricies diam, at facilisis arcu consequat ut. Vestibulum dignissim metus at risus rutrum dictum. Vivamus vehicula eros sed mattis porta. Aenean at posuere nulla, non vestibulum libero. Curabitur enim mi, placerat et pretium a, auctor vitae augue. Integer semper massa non eros sollicitudin lacinia.\r\n"
				+ "\r\n"
				+ "Duis eget ex tellus. Phasellus porta arcu et pellentesque hendrerit. Mauris venenatis ligula eu nulla posuere scelerisque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Quisque vel massa vel quam euismod ultrices. Nulla nec fermentum elit. Proin ac malesuada magna, sit amet iaculis dui. Donec pellentesque porttitor risus eu porta. Phasellus ultrices sed neque et suscipit. Etiam mattis egestas sollicitudin. Vivamus lectus erat, tristique non rhoncus et, laoreet a erat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam in malesuada enim. Nulla rhoncus mauris vitae dapibus dignissim. Vivamus pharetra erat vel finibus mattis.\r\n"
				+ "\r\n"
				+ "Pellentesque rutrum urna vitae aliquam tempus. Nulla aliquam maximus aliquam. Aliquam nec laoreet tortor. Nulla volutpat scelerisque sapien, id ullamcorper ligula pulvinar vel. Pellentesque vitae erat ultrices, rhoncus sem sit amet, elementum enim. Vivamus tellus nisl, accumsan non varius vel, luctus ut mi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris vel purus interdum, porttitor lorem in, rhoncus neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed bibendum ipsum sed enim ullamcorper, sed tempor mi interdum.\r\n"
				+ "\r\n"
				+ "Phasellus vitae enim fermentum odio finibus dapibus. Vestibulum at elementum sem, non mollis dolor. Donec et ante elementum, eleifend augue condimentum, commodo ipsum. Fusce facilisis nisl at rutrum interdum. Nam volutpat nisl libero, eu interdum massa ornare ut. Pellentesque lacinia, ex in ultrices maximus, massa nisl hendrerit urna, id cursus tellus nisl varius nunc. Etiam luctus ornare risus at vehicula. Suspendisse vulputate enim sit amet ex vestibulum pellentesque. Donec a blandit purus. Etiam elit nunc, imperdiet sit amet dolor a, fringilla aliquet ante. Pellentesque justo diam, cursus eu nulla eu, molestie blandit nisi.\r\n"
				+ "\r\n"
				+ "Nam eu mauris placerat, lacinia libero aliquam, tincidunt mi. Donec magna dolor, facilisis a eleifend in, consequat a nunc. Proin ullamcorper metus sit amet purus finibus, sed tempus quam dignissim. Nullam in tincidunt tellus. In lorem lorem, congue non leo finibus, viverra consectetur elit. Aliquam ut elementum justo. Quisque eget massa massa. Fusce vel felis dui. Nullam dapibus pharetra massa, sed tincidunt urna varius non.\r\n"
				+ "\r\n"
				+ "Proin sed nibh eleifend, elementum ligula et, cursus dui. Fusce sodales at diam eu tristique. Nunc aliquam fermentum tortor, at posuere libero vestibulum sit amet. Sed nibh magna, sagittis sed leo ac, ornare mollis elit. Aenean ornare velit quis nisl molestie, eget faucibus sapien dignissim. Donec fermentum ipsum dui, quis tristique est iaculis sit amet. Praesent et blandit turpis. In laoreet urna nulla, et egestas velit auctor id. Fusce pulvinar, neque ac sollicitudin convallis, tortor nisl accumsan dui, eget commodo diam turpis quis metus. Ut dolor justo, tincidunt ac bibendum et, vestibulum in mi. Morbi malesuada aliquet lobortis.\r\n"
				+ "\r\n"
				+ "Mauris mauris libero, bibendum vitae laoreet vel, vestibulum quis arcu. Vestibulum aliquam elit orci, at accumsan urna porttitor eget. Fusce a eros non metus hendrerit dapibus. Nam magna erat, sollicitudin vitae lobortis ut, convallis a leo. Ut molestie dolor semper diam sagittis ultrices. Nullam vel tortor vitae justo consectetur bibendum a eget neque. Nullam in leo non turpis sollicitudin fermentum. Sed suscipit viverra felis eget malesuada.\r\n"
				+ "\r\n"
				+ "Etiam mollis magna sed odio egestas, ac commodo dui venenatis. Suspendisse potenti. Curabitur suscipit auctor erat, ut lobortis neque tristique at. Phasellus bibendum cursus nunc. Vestibulum vitae nibh vel lectus accumsan vestibulum. Vestibulum in commodo quam, quis tempor erat. Sed lacinia faucibus suscipit. Maecenas elementum vulputate orci, vitae auctor massa pretium non. Sed vitae metus ante. Phasellus finibus lectus vitae dolor scelerisque maximus. Nullam imperdiet nulla arcu. Praesent eu nisl at erat auctor ultricies. Morbi a porttitor orci. Maecenas massa sem, pellentesque eu diam eu, aliquet molestie tellus.\r\n"
				+ "\r\n"
				+ "Ut nec elementum nunc. Fusce at arcu velit. Nunc finibus finibus quam, a lobortis mi accumsan in. Pellentesque ut malesuada enim. Aenean eu sem nisi. Nulla id purus eu nisl bibendum lacinia. Sed sit amet nisi sed nisl dictum tempor non non felis. Aliquam tempor mi vel arcu ultrices ultrices. Nulla vel placerat metus. Pellentesque sollicitudin justo tortor, auctor eleifend neque porta vitae. Vestibulum dictum venenatis tellus, ut aliquam ante fringilla vel. Nunc eget vulputate ante. Etiam at erat id quam egestas laoreet sed in mi. Aliquam velit urna, sodales et risus a, ultricies faucibus nulla. Aliquam erat volutpat. Cras sed est nec ante pulvinar tincidunt.\r\n"
				+ "\r\n"
				+ "Sed in mollis justo, elementum rutrum turpis. Praesent faucibus risus ut mi tempor tempus. Nullam eget arcu arcu. Suspendisse sagittis dui magna, quis gravida mauris molestie sed. Nulla vel mauris pharetra, condimentum mi ut, fringilla eros. Curabitur mi lacus, mattis sit amet dictum sit amet, euismod in felis. Quisque scelerisque, augue varius bibendum bibendum, ex felis placerat leo, tempus semper metus lacus ac leo. Sed vulputate condimentum ultricies. Vestibulum elementum risus eget blandit tincidunt. Etiam sed augue eros.\r\n"
				+ "\r\n"
				+ "Sed luctus vel augue imperdiet lacinia. Sed eget mi erat. In gravida varius nisl. In hac habitasse platea dictumst. Sed venenatis felis neque, in sollicitudin quam vestibulum quis. Suspendisse et faucibus risus. Aliquam faucibus egestas mollis. Curabitur posuere lobortis dolor et facilisis. Pellentesque aliquet hendrerit ante eu vehicula. Etiam feugiat, massa et aliquam dictum, ex mi mollis quam, non sagittis diam velit et tortor. Aenean elementum enim a sapien sollicitudin, vel tincidunt erat molestie. Cras vitae metus vitae lacus commodo luctus.\r\n"
				+ "\r\n"
				+ "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut nisi nunc, tincidunt ac cursus sit amet, condimentum sit amet mi. Integer facilisis fringilla augue, vel luctus arcu hendrerit sit amet. Donec eu nisl velit. Aliquam dolor lorem, lobortis a vehicula eu, pharetra sollicitudin mi. Nunc vel arcu a sapien imperdiet vulputate quis nec odio. Quisque vitae purus ut odio pulvinar ultrices. Fusce convallis laoreet pulvinar. Nam augue nisi, laoreet sed felis eu, convallis mollis justo. Donec hendrerit viverra tellus vitae molestie. Integer id dictum purus. Nulla eleifend elit ut varius cursus. Donec eu mi leo. Praesent nibh diam, convallis sagittis lorem id, consectetur congue nisl. Nullam velit lacus, pretium at nunc vitae, dictum lacinia arcu. Integer vel enim non mi faucibus congue.\r\n"
				+ "\r\n"
				+ "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dictum mattis venenatis. Quisque vitae dui eleifend, rhoncus tortor sed, pretium nibh. Pellentesque eget ante in ipsum efficitur eleifend. Curabitur pellentesque lacus eros, sed faucibus augue volutpat quis. Proin at enim sit amet tellus tristique aliquet. Sed egestas ultricies orci, id sagittis lectus eleifend ornare. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras malesuada urna lobortis dapibus ullamcorper. Sed non quam ac est consequat tempor interdum ac orci. Mauris fringilla dui sapien. Praesent justo lectus, ornare a aliquet a, ultricies non purus. Nam ac interdum odio. Suspendisse potenti. Praesent laoreet libero sit amet urna scelerisque aliquam.\r\n"
				+ "\r\n"
				+ "Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla venenatis orci eu varius pharetra. Curabitur dapibus diam pharetra erat consequat, vitae faucibus nulla facilisis. Suspendisse nibh lectus, fringilla vel tincidunt sed, suscipit venenatis nisi. Praesent urna magna, pretium at libero in, dapibus fringilla massa. Pellentesque nec porta odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean suscipit finibus nunc, a vehicula dui. Fusce porta eu massa vitae suscipit.\r\n"
				+ "\r\n"
				+ "Nullam ut odio mauris. Donec vel justo sed ante blandit porttitor id sit amet est. Vivamus rutrum eros et lectus vestibulum, dictum tincidunt metus mattis. Sed bibendum consequat augue, id finibus ex hendrerit ut. Morbi non finibus elit. Mauris efficitur nulla quis quam ornare, ut maximus ante luctus. Maecenas mattis nisl arcu. Quisque hendrerit augue eu elit consectetur, ut fringilla sem sollicitudin. Etiam laoreet massa arcu, vel congue diam volutpat nec.\r\n"
				+ "\r\n"
				+ "Mauris luctus est tellus, at mollis massa aliquet vitae. Quisque dui lectus, auctor sit amet tincidunt ac, dapibus scelerisque quam. Donec condimentum massa et arcu fringilla, consequat malesuada felis pharetra. Proin ultricies risus ac placerat semper. Pellentesque tincidunt lorem eu diam porttitor, a sollicitudin odio vestibulum. Morbi sit amet risus tristique, finibus nunc ac, varius leo. Vivamus elementum magna metus, et tincidunt mi bibendum vel. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec dapibus mauris in nunc venenatis, non posuere odio gravida.\r\n"
				+ "\r\n"
				+ "Sed pellentesque tristique congue. In viverra in sem feugiat rutrum. Etiam in justo vitae orci mollis scelerisque vitae id nisl. Nunc hendrerit suscipit purus non egestas. Quisque scelerisque vitae eros nec lacinia. Nam sodales congue velit, tristique ultrices orci pellentesque eget. Suspendisse accumsan nisi at diam lacinia molestie. Donec eget lacus nec dolor mollis posuere nec in elit. Cras aliquet, eros id rhoncus tempor, nisi ante hendrerit dolor, eget tincidunt eros mi eu nulla. Etiam ullamcorper, tortor sed pretium semper, neque urna suscipit turpis, id facilisis sapien massa nec massa. Praesent rhoncus sed enim eget egestas. Pellentesque aliquam lobortis nibh, at vulputate metus bibendum ac. Donec suscipit sapien id luctus vestibulum. Morbi vestibulum dapibus rhoncus.\r\n"
				+ "\r\n"
				+ "Integer ornare erat et commodo volutpat. Praesent quis velit in purus pellentesque rutrum quis et tellus. Suspendisse sodales mauris sit amet lacus gravida ornare. Duis suscipit molestie facilisis. Curabitur elementum urna eget neque ullamcorper iaculis. Ut consectetur, nisi pellentesque posuere pellentesque, sapien lectus euismod urna, eu accumsan nibh eros in erat. Aliquam dignissim, neque quis ultricies condimentum, justo lacus tempor nisi, eget rutrum velit ante id dui. Integer nec purus rhoncus, ultricies sapien at, euismod mi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed sed accumsan tellus. In hac habitasse platea dictumst.\r\n"
				+ "\r\n"
				+ "Sed porttitor turpis vitae nisl elementum blandit in nec lectus. Maecenas vehicula consectetur pulvinar. Cras id est ac turpis vestibulum venenatis vitae sed lacus. Nulla dictum euismod dui vitae posuere. Suspendisse varius vulputate volutpat. Duis semper porta sem nec blandit. Integer eget sapien pretium erat laoreet laoreet. Quisque et convallis lorem, eu faucibus risus. Aenean porta, justo id porta egestas, libero massa rutrum ex, sit amet feugiat leo mauris sit amet risus. Suspendisse viverra est vitae tincidunt tristique. Vestibulum sit amet malesuada orci, eu luctus enim.\r\n"
				+ "\r\n"
				+ "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ut ante velit. Vivamus scelerisque varius suscipit. Cras eleifend justo facilisis mauris vestibulum consectetur. Mauris gravida massa ut lorem ornare elementum. Ut eget vehicula felis, sed mattis est. Nam nec maximus nibh, in malesuada orci. Etiam interdum metus quis sapien euismod pretium. Cras pretium quis quam ac tincidunt.\r\n"
				+ "\r\n"
				+ "Morbi rhoncus est a nisi venenatis mollis. Morbi id gravida nulla, at pulvinar diam. Nunc quis condimentum diam. Curabitur sodales congue sapien, ut porta sapien tincidunt a. Proin ante diam, molestie sed placerat ac, sagittis at tortor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer faucibus ligula nulla, eu finibus urna pharetra dictum. Pellentesque sapien nisl, placerat nec rhoncus nec, dignissim vitae libero. Morbi cursus, nisi a scelerisque fermentum, lectus justo consectetur diam, id lacinia tellus nulla non sapien. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum aliquet sollicitudin sem a malesuada. Proin et erat efficitur lectus fringilla dignissim. Ut at lorem volutpat, viverra lacus ut, ornare enim. Morbi quis ultricies magna. Aliquam sed urna tincidunt, euismod sapien id, porttitor ex. In ut laoreet erat, at vulputate dui.\r\n"
				+ "\r\n"
				+ "Cras lobortis enim ut ante tincidunt, ut fringilla nibh bibendum. Aliquam at tristique massa, non accumsan ante. Nunc pharetra vel tortor sit amet consequat. Ut vulputate urna sit amet ex sagittis commodo. In leo arcu, pharetra non lacus eget, cursus porttitor sem. Aliquam convallis venenatis nisl. Vestibulum efficitur risus ex, at tincidunt nibh lobortis in. Cras ullamcorper orci ut lorem mattis, quis porta ligula lobortis. Donec sagittis, lectus vel fringilla consectetur, mi libero fermentum leo, quis imperdiet sem ante dictum massa. Aenean vitae commodo tortor, ut porta neque.\r\n"
				+ "\r\n"
				+ "Donec ante nisl, mattis pellentesque felis auctor, maximus interdum nisl. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque scelerisque scelerisque nunc, sed mollis lacus. Donec convallis porta eros, non semper dui luctus sit amet. Ut laoreet tincidunt diam, ut ultrices justo pulvinar a. Morbi blandit accumsan libero. Mauris bibendum condimentum sapien, sed dictum turpis accumsan eu. Sed et dictum justo.\r\n"
				+ "\r\n"
				+ "Nam iaculis, mauris imperdiet viverra consequat, arcu ante ullamcorper sem, eget lobortis lectus sem sed tortor. Suspendisse at dolor sed magna scelerisque placerat in a odio. Duis eleifend, ipsum eget bibendum convallis, ipsum turpis viverra nisl, eget sollicitudin nisi ex eu arcu. Proin sit amet massa nec ex laoreet dignissim. Mauris sagittis placerat velit et aliquet. Cras venenatis, elit a consectetur vulputate, ipsum lacus hendrerit nisl, et rutrum diam risus sed purus. Vestibulum lacinia arcu quis tempor ultricies. Nullam congue odio id nunc tempor accumsan. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis tellus nisi, ornare eget fermentum eu, dapibus vel odio. Vestibulum tempor at diam vel gravida. Morbi facilisis ultricies ornare. Sed eget congue lectus. Nulla et rutrum mauris. Praesent aliquet est dui, sed vehicula dui dapibus eu.\r\n"
				+ "\r\n"
				+ "Praesent vitae elit quis erat blandit varius. Suspendisse efficitur dolor tortor. Nullam lacinia libero vel urna maximus, in auctor mauris lobortis. Etiam pulvinar, arcu sed tincidunt laoreet, purus ipsum elementum leo, vitae convallis mauris tortor eu velit. Nullam volutpat, sem non consequat sollicitudin, purus urna molestie massa, at pellentesque sem libero eget lectus. Maecenas quis erat arcu. Vestibulum lorem nisi, sollicitudin at leo sit amet, sodales vulputate neque. Donec nec dolor et est ultricies lacinia a nec lacus. Phasellus mattis turpis lacus, et sodales nibh pretium id.\r\n"
				+ "\r\n"
				+ "Pellentesque facilisis accumsan metus, ut auctor velit maximus vel. Cras sit amet nibh ac mauris feugiat mollis ut ut sem. Suspendisse mattis volutpat semper. Donec vel leo feugiat, congue lectus vel, hendrerit mi. Fusce rutrum suscipit nulla sed ultricies. Fusce iaculis efficitur cursus. Maecenas vestibulum odio eget pretium egestas. Proin pharetra congue ipsum, vitae tristique ex. Donec commodo lorem ex, sit amet faucibus nisl mollis sit amet. Quisque quis sapien et elit dapibus pharetra ut eget lacus. Praesent tincidunt dictum libero, nec pharetra massa ullamcorper a.\r\n"
				+ "\r\n"
				+ "Pellentesque tempus quis quam eget euismod. Pellentesque tincidunt, nisi id porttitor rhoncus, purus lorem hendrerit turpis, sed feugiat sapien sem at velit. Sed nisl purus, tempus sed arcu porttitor, eleifend faucibus risus. Donec sit amet nunc a sem auctor semper. Phasellus ut porttitor lorem, vel euismod tortor. Sed viverra dolor eget felis vulputate sollicitudin. Duis vehicula erat id vehicula dictum. Aliquam tincidunt sem tortor, eget tempus diam vulputate eu. Mauris viverra venenatis enim sit amet sollicitudin. Praesent mattis fringilla ipsum, non varius neque tristique ac. Vestibulum nec tincidunt velit.\r\n"
				+ "\r\n"
				+ "Phasellus dapibus et justo eu faucibus. Proin convallis odio eget mattis rhoncus. Ut tincidunt mollis lacus id lacinia. Sed vitae odio massa. Aenean interdum magna et turpis volutpat malesuada. Cras auctor luctus lacinia. Sed eu nunc eget libero viverra fermentum at eu neque. Maecenas dictum risus eget est sodales pretium. Curabitur mi est, condimentum id egestas id, efficitur in mi. Vestibulum quam metus, rutrum et semper vitae, lacinia eu tortor. Sed maximus, nibh id rutrum condimentum, odio dolor euismod arcu, at egestas velit augue nec odio. Fusce vehicula congue neque eget aliquet. Mauris eu mauris turpis.\r\n"
				+ "\r\n"
				+ "Fusce nec neque rutrum, faucibus elit et, semper purus. Praesent ornare in metus vitae dictum. Quisque turpis dolor, malesuada eget arcu quis, mollis efficitur arcu. Donec aliquam risus sit amet diam aliquet, nec semper neque consectetur. Pellentesque nec vestibulum est. Mauris non finibus tortor, nec dignissim enim. Fusce rutrum a sem non accumsan. Proin in pulvinar leo, non dictum risus.\r\n"
				+ "\r\n"
				+ "Ut arcu ante, egestas dignissim sagittis id, volutpat vel turpis. Ut sagittis nunc sed orci pulvinar iaculis. Nullam tincidunt, ex a pellentesque ultricies, lorem mi varius odio, ut congue massa orci vitae elit. Vivamus sodales eu ligula eu interdum. Etiam accumsan lacus et nisl porttitor tristique et eget ligula. Suspendisse potenti. Duis vitae bibendum est. Proin posuere leo tellus, ut iaculis massa aliquet vitae.\r\n"
				+ "\r\n"
				+ "Cras posuere, metus ut sodales consectetur, ligula arcu feugiat odio, eu lacinia massa lacus et nisl. Fusce eget nisl nisl. Fusce id nisl pulvinar ligula posuere tempus in nec urna. Nullam malesuada rhoncus dignissim. Phasellus laoreet, dolor vitae tristique vestibulum, purus ligula ullamcorper libero, in faucibus purus arcu at risus. Etiam sed ornare felis, eget hendrerit turpis. Curabitur blandit pretium nisl, vel semper augue tincidunt at. Nulla placerat pulvinar nulla, sed tempor velit elementum ac. Cras imperdiet ante at lectus fermentum mollis pulvinar ac arcu. Praesent porttitor nulla quis sem sodales bibendum. Quisque et pellentesque lectus. Integer vitae efficitur urna, sed facilisis velit. Nam pretium tortor tempor velit molestie facilisis. Aenean ipsum risus, viverra eu sapien vitae, suscipit posuere leo. Fusce vehicula ante ornare erat feugiat, porta venenatis eros efficitur. Donec turpis nibh, pellentesque in iaculis sed, dictum eu nunc.\r\n"
				+ "\r\n"
				+ "Phasellus sollicitudin porta nibh tincidunt cursus. Aliquam eget purus sed dui mattis lacinia. Morbi massa mi, suscipit eu velit sed, tincidunt dignissim libero. Nam quis purus mauris. Ut pellentesque diam at ante volutpat, vitae ultricies orci laoreet. Donec pharetra eleifend velit, vitae consequat velit iaculis id. Aenean et aliquam est. Nunc luctus blandit massa, at semper turpis cursus eget. Duis rutrum mattis dui, quis vulputate massa mattis a.\r\n"
				+ "\r\n"
				+ "Duis iaculis nunc sem, fermentum pretium ipsum pellentesque at. Nunc pharetra magna ac commodo dignissim. Aliquam ullamcorper elit libero, blandit hendrerit mauris lacinia sit amet. Suspendisse et lorem est. Aenean justo nunc, sollicitudin eget consequat nec, suscipit id felis. Nulla in lectus sed turpis feugiat pellentesque a quis mauris. Nam vel interdum ante. Nam lobortis purus et malesuada euismod. Nunc ut lacus sollicitudin, interdum nisi non, porta dui.\r\n"
				+ "\r\n"
				+ "Nunc porttitor odio nec urna porttitor venenatis. Morbi eget felis turpis. Vestibulum semper velit sit amet tempus lacinia. Maecenas luctus ullamcorper turpis sodales condimentum. Quisque vulputate fringilla odio, et iaculis elit ornare id. Donec scelerisque facilisis justo vitae consequat. Praesent dignissim interdum elit eu pellentesque.\r\n"
				+ "\r\n"
				+ "Praesent molestie quam ac blandit hendrerit. Praesent a mollis purus, sed mollis diam. Praesent aliquet tellus sit amet est gravida, sed cursus erat convallis. Aliquam cursus ligula in ligula consequat, a molestie diam efficitur. Maecenas sodales ex risus, ultricies viverra mi suscipit ac. Praesent consectetur ligula vel ullamcorper tempor. Donec auctor sollicitudin massa in sollicitudin. Donec pulvinar finibus est, sit amet facilisis risus. Vestibulum volutpat justo sit amet rutrum molestie. Vivamus odio ex, laoreet eget pretium id, tincidunt venenatis nunc. Suspendisse sapien velit, condimentum vitae lacus et, luctus fringilla velit. Maecenas efficitur sapien mi, vitae efficitur sem malesuada at. Aliquam at urna non metus vehicula ultrices nec nec lorem.\r\n"
				+ "\r\n"
				+ "Cras tempor lectus et dolor aliquam, eget iaculis metus convallis. Etiam ac lectus sed erat commodo dictum fringilla non neque. Integer quis ultricies metus. Sed tincidunt leo et sem tempus, sit amet viverra augue rhoncus. Sed dapibus nisl nisi, sed laoreet lorem aliquet non. Ut euismod molestie erat nec malesuada. Aliquam erat volutpat. Donec consectetur diam libero, quis efficitur justo semper aliquam. Aenean dignissim ante a nisl condimentum accumsan. Proin ut purus in lorem commodo tincidunt a et sem. Curabitur feugiat feugiat dolor sit amet aliquet.\r\n"
				+ "\r\n"
				+ "Vestibulum convallis rhoncus nisl, a porta ante facilisis ut. Cras ante lacus, aliquam nec interdum sit amet, faucibus semper velit. Curabitur sed justo eu tortor eleifend volutpat. Curabitur ligula mi, porttitor non risus eget, facilisis aliquam nulla. Cras fringilla justo mauris, congue sodales eros vehicula in. Nulla aliquam rutrum est, id convallis est cursus id. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum vitae semper arcu. Curabitur sit amet sagittis odio. Quisque quam augue, lacinia ut efficitur a, vehicula ut purus. Sed eget elit orci. Sed bibendum ex nulla, sed auctor ipsum viverra id. Mauris sed sapien mollis, commodo turpis nec, imperdiet nisl.\r\n"
				+ "\r\n"
				+ "Sed blandit venenatis tortor, id cursus eros aliquet a. Nunc leo nunc, consequat id consequat et, porttitor a velit. In gravida in turpis vitae commodo. Quisque at est tristique, vestibulum nisi non, suscipit arcu. Integer scelerisque lectus eget quam aliquam auctor. Aenean commodo at leo at porta. Integer sagittis magna sollicitudin metus scelerisque, vitae pellentesque lectus lobortis. Phasellus venenatis elementum tincidunt.\r\n"
				+ "\r\n"
				+ "Sed nec posuere massa. Cras semper nec libero eu rutrum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque dapibus, ante sit amet interdum iaculis, dolor orci auctor diam, semper commodo sem quam quis magna. Maecenas quis euismod leo. Cras eget semper erat, sit amet consequat est. Nullam lacinia leo quis augue gravida feugiat. Nulla facilisi. Vestibulum ultricies ipsum et enim volutpat pellentesque. Curabitur sagittis luctus leo quis ultricies. Vivamus vitae mauris laoreet felis pulvinar dignissim. Integer eu turpis non urna finibus pellentesque.\r\n"
				+ "\r\n"
				+ "Nullam fringilla purus sed nisi feugiat, nec ullamcorper lectus vehicula. Aenean lacus nisl, cursus eget tristique ornare, consectetur a quam. Quisque elementum molestie lacus ut mattis. Mauris congue nibh ac enim pharetra lacinia ac et justo. Nullam sed sodales sapien. Aliquam bibendum pretium nisl sed fermentum. Nunc euismod malesuada facilisis. Vestibulum ornare ante et lorem imperdiet, a imperdiet lectus ullamcorper. Donec mauris dui, consequat sit amet metus vel, tempor lacinia felis. Integer luctus massa ante, at efficitur nulla mattis nec. Phasellus ac quam non ante pulvinar dictum sit amet at est.\r\n"
				+ "\r\n"
				+ "In molestie neque at interdum congue. Curabitur scelerisque felis sem. Fusce cursus felis et ante rhoncus iaculis. Nulla tempus dictum bibendum. Vivamus a nibh neque. Donec nisl ligula, faucibus at tortor eget, gravida vehicula sapien. Nam eget ipsum risus. Aliquam ut est odio. Nam nulla ligula, auctor vitae feugiat ac, feugiat vitae tortor. Etiam metus augue, suscipit rutrum dictum id, facilisis quis sem. Proin dictum convallis ex ac laoreet.\r\n"
				+ "\r\n"
				+ "Nullam venenatis tellus in augue varius condimentum. Mauris facilisis aliquam lacus, ac cursus nunc sagittis ac. Vivamus id enim lacinia, finibus augue at, molestie felis. Praesent posuere laoreet condimentum. Curabitur suscipit molestie augue, nec volutpat sem posuere in. Ut diam nibh, luctus nec justo id, dictum tempor purus. Phasellus quis tempus metus. Quisque metus turpis, volutpat nec sapien id, consequat efficitur sapien. Sed sit amet placerat ipsum, interdum tincidunt mauris. Maecenas sit amet elit eget est hendrerit pharetra feugiat a turpis. Donec et ex sit amet diam vehicula consequat a sit amet lorem. Phasellus posuere nec odio in fringilla. Donec diam diam, convallis ut enim a, pharetra lobortis lectus. Suspendisse eget venenatis arcu, vel sollicitudin quam.\r\n"
				+ "\r\n"
				+ "Sed id lectus congue, interdum eros quis, lacinia libero. Etiam condimentum consequat blandit. Nulla facilisi. Nam quam lectus, lacinia vel nisl ut, viverra pellentesque nibh. Nunc sollicitudin sapien ligula, sed rhoncus ipsum scelerisque eget. Integer mauris odio, tempor eget lorem vel, suscipit venenatis nunc. Praesent tincidunt placerat felis et tempor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque mollis, dui ac molestie vulputate, ante arcu scelerisque nulla, at congue orci augue at massa. Proin interdum, tortor a facilisis imperdiet, velit ex consectetur lacus, vitae placerat purus libero ac ante. Vivamus sagittis augue lectus, eu laoreet felis ultrices a. Duis ac faucibus sem. Aliquam at est in justo imperdiet dapibus quis in turpis. Etiam consequat nisl consequat augue fermentum hendrerit. Fusce eu dui quis leo varius molestie a eu purus. In non sagittis urna, et dignissim odio.\r\n"
				+ "\r\n"
				+ "Duis dignissim sed augue vitae feugiat. Ut bibendum dolor quis lobortis auctor. Nullam hendrerit id turpis quis vestibulum. Duis tellus augue, semper vel scelerisque non, lobortis nec quam. Proin id ullamcorper felis, nec euismod turpis. Etiam placerat justo sed commodo varius. Integer pharetra augue vulputate ex aliquet imperdiet. Sed dictum sem a urna laoreet, at mollis lorem auctor. Sed ornare lorem a tincidunt sollicitudin. Donec ullamcorper odio in mollis eleifend. Sed risus elit, venenatis at feugiat in, ultrices id purus. Ut aliquet feugiat nunc efficitur pharetra. Phasellus ut dolor molestie, iaculis tellus vitae, placerat ipsum. Fusce tempor accumsan justo non ultrices.\r\n"
				+ "\r\n"
				+ "Morbi euismod iaculis lectus sit amet auctor. Nunc eget eros eu mauris scelerisque aliquam id vel odio. Duis dignissim nibh ex, at volutpat ipsum feugiat ac. Etiam a malesuada enim, non eleifend est. Praesent tincidunt aliquet pharetra. Vestibulum vel rhoncus lorem. Cras at mauris consectetur, pretium ligula nec, ullamcorper odio.\r\n"
				+ "\r\n"
				+ "Vivamus blandit enim sit amet eros consectetur, vitae venenatis leo sagittis. Phasellus non odio facilisis, suscipit orci quis, feugiat nisi. Cras quis semper tellus. In volutpat arcu consequat augue sollicitudin tempor. Nullam faucibus convallis viverra. Integer velit metus, ultricies porttitor pharetra ac, ultricies a quam. Nulla sodales diam diam, id dignissim lacus sodales ac. Aenean eu ex non dui lacinia placerat. Curabitur dictum neque quis quam mattis, vitae aliquet ipsum sollicitudin. Vivamus ornare nunc vel tortor bibendum molestie. Sed urna orci, tincidunt at consectetur ac, facilisis et risus. Vivamus ut risus sed nisl sodales luctus. Quisque scelerisque placerat ipsum at mollis.\r\n"
				+ "\r\n"
				+ "Curabitur tincidunt ornare interdum. Quisque massa massa, vestibulum sit amet placerat vitae, iaculis vitae nibh. Suspendisse facilisis posuere mi, at rutrum ante vestibulum eget. Proin auctor consequat consectetur. Sed eget odio suscipit sapien facilisis molestie. Aenean eleifend efficitur leo, id rhoncus purus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce pharetra justo neque, vel imperdiet magna blandit non. Mauris eleifend scelerisque nibh.\r\n"
				+ "\r\n"
				+ "Etiam rutrum ut metus non placerat. Etiam ex nibh, sagittis eget magna sit amet, pellentesque efficitur dolor. Nullam non eros lacinia, luctus nisl et, tempus dui. Nunc at tellus at nulla aliquam scelerisque non mollis nulla. Pellentesque nunc dolor, gravida quis ante id, vehicula ornare dui. Maecenas sed lacus urna. Aenean interdum odio pretium, mollis leo nec, finibus lorem. Sed lobortis aliquet lacus, vel efficitur nunc semper in. Aliquam placerat eu augue non dignissim. Nam pharetra eros in metus ultricies pharetra. Nunc mi nisi, rhoncus in pulvinar dictum, consequat vitae nibh. Nam eget turpis purus. Cras congue nunc nulla, ut euismod orci ullamcorper gravida.\r\n"
				+ "\r\n"
				+ "Maecenas ac varius arcu, ac condimentum erat. Proin diam dolor, condimentum ut lectus vitae, imperdiet feugiat leo. Phasellus pellentesque sapien quam, id mollis est euismod quis. Mauris aliquet velit eu erat eleifend imperdiet. In risus nisl, rutrum non tincidunt non, mollis dictum tellus. In hac habitasse platea dictumst. Vestibulum id ultricies orci. Cras pellentesque, erat facilisis pretium maximus, nisi dui consectetur turpis, vitae vestibulum risus nisl non nunc. Curabitur rhoncus nulla eros, in malesuada felis malesuada at. Vivamus eu ligula vitae ex tincidunt aliquet. Maecenas et blandit nisl. Quisque et ligula vitae ex semper scelerisque. Aliquam tristique auctor commodo.\r\n"
				+ "\r\n"
				+ "Aenean vestibulum augue vel elit convallis imperdiet. Maecenas vitae aliquam risus. Etiam maximus massa ligula, quis finibus urna ullamcorper elementum. Morbi eu elit risus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent sagittis tempor lectus, non tristique augue malesuada sit amet. Integer quis nisi ac nunc gravida commodo. Aliquam quis facilisis metus. Interdum et malesuada fames ac ante ipsum primis in faucibus.\r\n"
				+ "\r\n"
				+ "Cras convallis gravida tempus. Etiam sagittis mi et leo venenatis tempor. Nulla non nisi neque. Donec gravida sit amet est egestas fermentum. Nullam tempor arcu elit. Etiam nec augue elementum, lobortis leo quis, sagittis ipsum. Aenean sit amet tristique nisi, quis volutpat lorem. Sed hendrerit suscipit vulputate. Aenean rhoncus dictum nisi, suscipit condimentum augue molestie ut.\r\n"
				+ "\r\n"
				+ "Suspendisse et nisl sed erat malesuada vulputate scelerisque et tellus. Pellentesque sodales felis imperdiet tortor interdum, at eleifend felis viverra. Duis arcu leo, pretium vel est ut, placerat interdum dui. Phasellus in quam tellus. Aenean sed risus tellus. Cras elit purus, vehicula nec rhoncus at, elementum vitae urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla ac nulla nulla. In fermentum diam nunc, vel venenatis lectus condimentum in. Sed et dolor sit amet leo dignissim ullamcorper. Vivamus efficitur felis nec velit blandit, at maximus eros gravida. Phasellus elementum sapien vitae nisl porta volutpat. Sed consectetur pellentesque sapien.\r\n"
				+ "\r\n"
				+ "In interdum ipsum erat, nec pulvinar odio pellentesque sit amet. Pellentesque porttitor dui nibh. Duis in scelerisque arcu. Curabitur iaculis elit ex, in fringilla tortor tincidunt vel. Suspendisse ornare risus a justo varius, id pellentesque mauris euismod. Quisque bibendum molestie dui, a sodales tellus pellentesque sed. Nulla lorem sapien, vestibulum vel dui consectetur, ultrices sodales quam. Integer pellentesque tristique neque a finibus. Vivamus blandit feugiat volutpat. Morbi accumsan venenatis aliquet. Praesent aliquam molestie dui. In fermentum, nisi quis efficitur porta, lectus dolor gravida nulla, ut gravida lorem ante id est. Curabitur ac vehicula lectus. Donec sed eros a nisl commodo euismod non ut nibh. Aliquam id varius massa. Vestibulum volutpat sed libero quis venenatis.\r\n"
				+ "\r\n"
				+ "Etiam vehicula metus leo, ac iaculis elit congue eu. Nulla imperdiet, tortor eu auctor tempor, eros diam ullamcorper ipsum, ac hendrerit lorem tortor id erat. Nullam nec pulvinar ipsum. Fusce mattis finibus risus eu scelerisque. Suspendisse orci odio, eleifend non felis eu, sagittis semper erat. Aliquam vehicula, velit commodo dignissim semper, enim quam fermentum nulla, eget commodo sapien sem a est. Nam quis ligula pulvinar, cursus tortor nec, rhoncus turpis. Quisque ornare vestibulum venenatis. Maecenas laoreet tellus sapien, ut aliquet neque fermentum eget. Donec id dui sollicitudin mi porta pulvinar. Proin eget aliquam eros. Nam sollicitudin turpis ut massa sollicitudin, nec gravida ipsum sollicitudin. Nunc sapien eros, gravida a tristique in, ultrices non turpis.\r\n"
				+ "\r\n"
				+ "Vivamus placerat dapibus dictum. Donec scelerisque accumsan finibus. Nulla lacinia, lectus id sodales feugiat, elit urna sodales ligula, ac dictum magna diam condimentum dolor. Fusce in lectus nibh. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus a varius ex, nec interdum ipsum. Ut eu justo nec ligula bibendum pulvinar. Vivamus mollis odio justo, ac vulputate neque tincidunt id. Praesent ligula sem, volutpat a dolor tincidunt, scelerisque consequat lorem. Donec eu auctor tortor, eu rutrum nisl. Proin pulvinar libero at leo rutrum, ut ultrices arcu dictum. Pellentesque lacinia ut ex in bibendum. Praesent quis placerat purus. Curabitur fermentum velit vel leo fringilla rutrum. Sed sed dui scelerisque, mollis nunc nec, eleifend risus. Cras in dui metus.\r\n"
				+ "\r\n"
				+ "Integer non orci eget quam semper rhoncus. Duis id dolor et turpis porta hendrerit nec sit amet nibh. Duis laoreet mollis augue, vulputate fringilla turpis bibendum euismod. Phasellus varius euismod ligula in accumsan. In eu magna tempor, placerat nisi vel, gravida lorem. Aenean quis mi sit amet tellus pulvinar faucibus. Praesent metus mi, ultrices interdum magna aliquam, interdum porttitor nisl.\r\n"
				+ "\r\n"
				+ "Maecenas lacinia massa posuere, rutrum dui sit amet, tempor felis. Morbi vestibulum ante turpis, vitae aliquet turpis convallis sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam faucibus dolor at leo efficitur malesuada. Praesent at risus quam. Ut nec risus congue, scelerisque dolor sed, consectetur justo. Suspendisse venenatis, nunc nec blandit tincidunt, diam felis tempor nibh, non fermentum purus eros in magna. Integer ut leo mattis, ultricies velit sit amet, ullamcorper massa. In rutrum elit non viverra efficitur. Fusce vel condimentum nisi. Maecenas tincidunt lorem lobortis nulla maximus, quis maximus nisl hendrerit. In consequat, massa a convallis tincidunt, nulla libero sagittis lorem, et venenatis odio quam a tellus. Quisque orci ipsum, vehicula sit amet suscipit at, mattis ac odio. Sed porta est in massa pulvinar egestas. Fusce et mattis mauris. Nullam auctor dignissim lorem, sit amet mattis sapien.\r\n"
				+ "\r\n"
				+ "Maecenas laoreet, leo eu pulvinar blandit, velit nulla maximus magna, sit amet mollis arcu turpis sed nisi. Suspendisse finibus dolor quis libero dapibus, laoreet rhoncus arcu faucibus. Morbi sagittis arcu et velit mattis, eget vulputate felis interdum. Pellentesque odio purus, faucibus eu diam vel, blandit vestibulum sem. Proin luctus dolor eu neque convallis, at euismod lectus rutrum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam orci urna, mollis at tempus in, sollicitudin ut sem. Sed tellus ex, congue non gravida ac, eleifend vel urna. Aenean congue in magna non tempor. In pretium fermentum sollicitudin. Fusce sit amet ipsum nec nunc sagittis viverra. Nam sed odio turpis. Curabitur nisl turpis, vehicula non lacinia at, ullamcorper et purus.\r\n"
				+ "\r\n"
				+ "Nulla quis tincidunt sem. Sed sit amet dolor enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sit amet urna bibendum, accumsan libero ut, vestibulum est. In eget malesuada sapien, ut sollicitudin elit. Duis in orci eget magna porta egestas faucibus nec sem. In lobortis metus eu justo eleifend, nec blandit purus gravida. Etiam viverra mauris quis ante semper blandit. Fusce at quam ornare, laoreet diam quis, vehicula odio. Ut molestie metus nibh, eu porta arcu laoreet auctor.\r\n"
				+ "\r\n"
				+ "Aliquam erat volutpat. Pellentesque porttitor, purus eu interdum tempor, tortor elit vehicula augue, et tincidunt magna magna eu justo. Donec hendrerit rutrum libero quis pretium. Proin aliquam aliquam dolor, ut lacinia libero pretium non. In hac habitasse platea dictumst. Praesent eros odio, imperdiet vitae ipsum at, fringilla venenatis tortor. Sed eget vehicula augue. Quisque interdum, ligula a accumsan hendrerit, orci tellus porttitor orci, a porta enim odio vitae dui.";
		
		
		
		
//		s="My string fdhgfdsgfdsfdsdfsfsddsf";
//		s="My string";
		String myReversedString;
		double[] testTimes= {0,0,0,0};
		//ArrayList<Integer> myInts =new ArrayList<>();
		//Integer bob =65;
		
		
		
		
		long startTime;
		long endTime;
		
		System.out.println();
		System.out.println("Reverse String w/ Char Array");
		startTime=System.nanoTime();
		myReversedString=reverseStringWChar(s);
		endTime=System.nanoTime();
		testTimes[0]=endTime-startTime;
		System.out.println("It took "+ (endTime-startTime) +" nanoseconds.");
		//System.out.println(myReversedString);
		
		System.out.println();
		System.out.println("Reverse String w/ StringBuilder");
		startTime=System.nanoTime();
		myReversedString=reverseStringWithBuilder(s);
		endTime=System.nanoTime();
		testTimes[1]=endTime-startTime;
		System.out.println("It took "+ (endTime-startTime) +" nanoseconds.");
		//System.out.println(myReversedString);
		
		System.out.println();
		System.out.println("Reverse String with + (concatenation)");
		startTime=System.nanoTime();
		myReversedString=reverseString(s);
		endTime=System.nanoTime();
		testTimes[2]=endTime-startTime;
		System.out.println("It took "+ (endTime-startTime) +" nanoseconds.");
		//System.out.println(myReversedString);
		
		System.out.println();
		System.out.println("Reverse String with .concat()");
		startTime=System.nanoTime();
		myReversedString=reverseStringWithConcat(s);
		endTime=System.nanoTime();
		testTimes[3]=endTime-startTime;
		System.out.println("It took "+ (endTime-startTime) +" nanoseconds.");
		//System.out.println(myReversedString);
		
		int min=0;
		for(int i=0; i<4; i++) {
			
			if (testTimes[i]<testTimes[min]) {
				min=i;				
			}
		}
		System.out.println("The fastest calculation was test "+ (min+1));
		
	}
	
	// Time Complexity = O(n) <- where n = the length of the string
	// Space Complexity (additional space we are taking up for the algorithm) = O(n)
	// Which one is more important in general? Time, because Space is pretty cheap nowadays
	public static String reverseStringWChar(String s) {
		String myReversedString;
		char[] charArray = new char[s.length()];
		for(int i=s.length(); i>0; i--) {
			charArray[s.length()-i]=s.charAt(i-1);
		}
		myReversedString=new String(charArray);
		return myReversedString;
	}
	
	// Time complexity = O(n)
	// Space complexity = O(n)
	public static String reverseStringWithBuilder(String s) {
		StringBuilder sb=new StringBuilder();
		for(int i=s.length(); i>0; i--) {
			sb.append(s.charAt(i-1));
		}
		return new String(sb);
	}
	
	// Time Complexity = O(n^2)
	// Space Complexity = O(n) (depends on garbage collector kicking in)
	public static String reverseString(String s) {
		String myReversedString="";
		for(int i=s.length(); i>0; i--) {
			myReversedString += (s.charAt(i-1));
		}
		return (myReversedString);
	}
	
	// Time Complexity = O(n^2)
	// Space Complexity = O(n) (depends on garbage collector kicking in)
	public static String reverseStringWithConcat(String s) {
		String myReversedString="";
		for(int i=s.length(); i>0; i--) {
			myReversedString = myReversedString.concat(String.valueOf(s.charAt(i-1)));
		}
		return (myReversedString);
		
	}
	
}
